### PR TITLE
renamed benchmark, better documented file

### LINKED ISSUE #84: Measure performance
For our AMS poster/paper we need to measure the performance of the zstandard, the bitgroom, and both together. (see #33)

### PR DESCRIPTION
**Pull request by edwardhartnett**
Fixes #84 
Part of #33

Renamed test, better documentation.

I added the bitgroom filter. 

Here's some results:
image

image

### CODE REVIEW

**Comment by edwardhartnett** [comment]
@czender I set nsd to 5 for all vars for the bitgroom filter. Does that make sense? Or would different vars usually have different nsd?

Is this nsd after the decimal? Or total number of significant digits? Sorry, you probably told me that once...

Also this is about all I have in mind for performance tests before I write the paper. If you have any further suggestions, nows the time to make them. Of course, there's also always next version. ;-)

**Comment by edwardhartnett** [comment]
Here's some raw results with nsd set to 5:

```
*** Checking Performance of filters.
*** Checking Zstandard vs. zlib performance on large climate data set...
compression, level, nsd, read time (s), write time (s), re-read time (s), file size (MB)
none, 0, 0, 1.452, 2.119, 0.540, 979.84
zstd, 1, 0, 1.425, 2.324, 1.271, 616.11
zlib, 1, 0, 1.420, 21.617, 3.746, 612.83
bitgroom, 0, 5, 1.417, 1.641, 0.483, 979.89
bitgroom_zstd, 1, 5, 1.418, 2.724, 1.221, 574.95
bitgroom_zlib, 1, 5, 1.452, 20.231, 4.234, 562.51
ok.
*** Tests successful!

```
Here's some with nsd set to 3:

```
*** Checking Performance of filters.
*** Checking Zstandard vs. zlib performance on large climate data set...
compression, level, nsd, read time (s), write time (s), re-read time (s), file size (MB)
none, 0, 0, 1.445, 2.045, 0.556, 979.84
zstd, 1, 0, 1.422, 2.944, 1.300, 616.11
zlib, 1, 0, 1.423, 22.283, 3.809, 612.83
bitgroom, 0, 3, 1.422, 1.656, 0.502, 979.89
bitgroom_zstd, 1, 3, 1.455, 3.507, 1.252, 454.14
bitgroom_zlib, 1, 3, 1.437, 15.379, 4.055, 417.39
ok.
*** Tests successful!
```

**Comment by czender** [comment]
FIFO:
NSD is total number of significant digits.

The results look pretty good. A few small surprises, like how Zlib is better than Zstd as a post-quantization filter despite starting with the same CR without quantization.

Ideally a scientist would optimize NSD on a per-variable basis, as described in the GMD BitGroom paper. However, in real life, NSD=3 is a good choice for not too conservative and not too liberal quantization of all variables. As you know, BG is quantization so achieves no compression by itself so please do not plot BG without the subsequent Zlib or Zstd pass.

**Comment by edwardhartnett** [comment]
I plotted BITGROOM by itself to examine the timing and to ensure (and demonstrate) that it comes up with the same size data as the non-compressed.

I can take it out for the paper. I will also change the nsd to 3 for the benchmark.

**Comment by edwardhartnett** [comment]
image
image

**Pull request merged**
