### PR TITLE
turned bitgroom back on

### PR DESCRIPTION
**Pull request by edwardhartnett**
@czender why does this not work? Any clue?

### CODE REVIEW

**Comment by edwardhartnett** [comment]
netcdf-c logging tells me:

```
		*** NetCDF-4 Internal Metadata: int_ncid 0x0 ext_ncid 0x10000
		FILE - path: tst_zstandard_bitgroom_zstandard.nc cmode: 0x11009 parallel: 0 redef: 0 fill_mode: 0 no_write: 0 next_nc_grpid: 1
		 GROUP - / nc_grpid: 0 nvars: 1 natts: 0
		 DIMENSION - dimid: 0 name: X len: 100 unlimited: 0
		 DIMENSION - dimid: 1 name: Y len: 100 unlimited: 0
		 VARIABLE - varid: 0 name: Wacky_Woolies ndims: 2 dimids: 0 1 storage: chunked
			nc4_rec_write_groups_types: grp->hdr.name /
			nc4_rec_write_metadata: grp->hdr.name /, bad_coord_order 0
			var_create_dataset:: name Wacky_Woolies
HDF5-DIAG: Error detected in HDF5 (1.10.7) thread 0:
  #000: H5D.c line 152 in H5Dcreate2(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #001: H5Dint.c line 338 in H5D__create_named(): unable to create and link to dataset
    major: Dataset
    minor: Unable to initialize object
  #002: H5L.c line 1605 in H5L_link_object(): unable to create new link to object
    major: Links
    minor: Unable to initialize object
  #003: H5L.c line 1846 in H5L__create_real(): can't insert link
    major: Links
    minor: Unable to insert object
  #004: H5Gtraverse.c line 848 in H5G_traverse(): internal path traversal failed
    major: Symbol table
    minor: Object not found
  #005: H5Gtraverse.c line 624 in H5G__traverse_real(): traversal operator failed
    major: Symbol table
    minor: Callback failed
  #006: H5L.c line 1652 in H5L__link_cb(): unable to create object
    major: Links
    minor: Unable to initialize object
  #007: H5Oint.c line 2496 in H5O_obj_create(): unable to open object
    major: Object header
    minor: Can't open object
  #008: H5Doh.c line 300 in H5O__dset_create(): unable to create dataset
    major: Dataset
    minor: Unable to initialize object
  #009: H5Dint.c line 1239 in H5D__create(): unable to set local filter parameters
    major: Dataset
    minor: Unable to initialize object
  #010: H5Z.c line 937 in H5Z_set_local(): local filter parameters not set
    major: Data filters
    minor: Error from filter 'set local' callback
  #011: H5Z.c line 866 in H5Z__prepare_prelude_callback_dcpl(): unable to apply filter
    major: Data filters
    minor: Error from filter 'can apply' callback
  #012: H5Z.c line 748 in H5Z__prelude_callback(): required filter was not located
    major: Data filters
    minor: Object not found
  #013: H5Z.c line 1284 in H5Z_find(): required filter 0 is not registered
    major: Data filters
    minor: Object not found
ERROR: file nc4hdf.c, line 987.
NetCDF: HDF error
```

**Comment by edwardhartnett** [comment]
@czender this is an important problem and I would really like this to work before we release...

**Comment by czender** [comment]
I will try to look at this today. What is the context of the failure? Is this a multi-filter test that require netCDF 4.8.0-dev and the test still fails even though that is loaded?

**Comment by edwardhartnett** [comment]
Yes, this is a multifilter test that requires netcdf-c master, which is built in the new workflow ("multifilter with netCDF master")

The same multifilter code seems to work fine in tst_eamv1_benchmark.c, but in tst_zstandard.c it fails.

**Comment by edwardhartnett** [comment]
I will close this and add some more testing for handling multifilters...

**Comment by czender** [comment]
Aha. Great catch. I do not see where `filterids` is free'd in the multi-filter portion of `nc_inq_var_zstandard()`. Looks like a memory leak?

**Comment by edwardhartnett** [comment]
Crap! I just released.

Why did our memory checking not catch this? Because it does not work with
multifilters. So I'll add an issue for that...

**Pull request closed without merging**
